### ISSUE TITLE
Quest name search capability

### ISSUE THREAD

**Issue by ed5464215** [reubengann/Witcher3MapViewer#1]
This is an awesome accomplishment. I'd played with Atvaark's code a while back trying to print out completed quest names and didn't get very far. Great job!

Would it be very difficult to add a search field that would jump to the first matching text in a quest name? (the answer is 'yes' for me I'm afraid)

**Comment by reubengann** [comment]
I think this would be a good feature, but I'm not sure how it would work from an interface standpoint. Having a text box that acted as a filter might work. Another possibility is that it could work like Windows File Explorer does, where typing the first letter jumps to the first item. The quests aren't listed alphabetically, but repeated keypresses could step through them. Not sure; do you have an opinion?

**Comment by ed5464215** [comment]
Yeah I think the text box would work nicely. Similar to the Find command in Firefox, maybe with an up/down arrow to jump to the prev/next occurrence. No need to be case sensitive.

Has your software been mentioned on the Reddit Witcher forum? It's a godsend for those of us with WQCD (Witcher3 Quest Completion Disorder).  I saw it mentioned today on the modding discord.

**Comment by reubengann** [comment]
Ok, I will work on a solution. Shouldn't take too long.

I actually wasn't sure if the program was usable enough to try to publicize it on a big forum like reddit, so I solicited comments on the Steam forums. However, that didn't garner much response, and tbh I have been sidetracked with other stuff. If you think it's worth it, please do let people know. Otherwise, I may try posting something at some point.

**Comment by reubengann** [comment]
Please check latest build or pull request. Should meet your needs.

**Comment by ed5464215** [comment]
Perfect! I searched for 'duck, duck, goose', and wasn't expecting 'lilac and gooseberries'...

Great job. Will recommend.  Builds fine on VS2017.

Do you think creating an installer is counter-productive since it scares away some users when it asks permission to install? Better to just point them to the .zip?

**Comment by reubengann** [comment]
I prefer not to have an installer, since I don't write or read the registry or do much of anything system-wide. The only system interaction is through the settings, but that works without an install. The zip file should be openable by all active versions of Windows, so I think that's fine.

**Comment by ed5464215** [comment]
Makes sense. You can close this then. It works as advertised!

**Comment by ed5464215** [comment]
Posted to /r/witcher here:

https://www.reddit.com/r/witcher/comments/6pcbys/finally_a_way_list_search_and_automatically_track/

Thanks again!
