### ISSUE TITLE
What license do you use? Can I reuse parts of your project?

### ISSUE THREAD

**Issue by pingween** [reubengann/Witcher3MapViewer#15]
Hi!

I'm entertaining the idea of creating a web version of tracking quests for Witcher 3 as a hobby project, very similar to yours, maybe without the map. I play on Xbox, so I could only manually update completed quests anyway and using a checklist on a tablet from a browser would be more convenient for console players than a windows program.

I'd like to re-use Quests.xml and Gwent.xml as the basis of my webapp. You made an awesome job collecting these, it would be great I could build upon them.

I couldn't find any indications on the licensing policy for Witcher3MapViewer on the project page. Does your policy allow reusing  the parts I mentioned? 

Thank you.

ps.: also, trying on Windows I have the same issue as https://github.com/reubengann/Witcher3MapViewer/issues/12 I couldn't check any quests manually.

**Comment by reubengann** [comment]
No restrictions. Please make use of the project any way you like.
