### ISSUE TITLE
Fail to start on automatic mode

### ISSUE THREAD

**Issue by MantasZilinskas** [reubengann/Witcher3MapViewer#18]
Release: https://github.com/reubengann/Witcher3MapViewer/tree/0.4
Game version: v 4.00
Settings: automatic mode with all checkboxes ticked
Issue: fails to start after `Save and close`

Seems to fail in this part of code https://github.com/reubengann/Witcher3MapViewer/blob/b80a175506252d14df6a4d886e4213ebb56e2c4e/Witcher3MapViewer/Witcher3SaveFile.cs#L1494 as it receives code `23`

**Comment by MantasZilinskas** [comment]
[QuickSave_52586_7e703800_4f9294f.zip](https://github.com/reubengann/Witcher3MapViewer/files/10420869/QuickSave_52586_7e703800_4f9294f.zip)

**Comment by reubengann** [comment]
Thanks for reporting. Looks like you're on the next gen patch version. Not
surprising that they made changes to the file format.

I'll see if I can fix when I have a chance. If you feel confident in the VS
debugger, if would be helpful to know where you see the code failing.

**Comment by MantasZilinskas** [comment]
Adding the extra condition `code2 != 23` seems to fix things. Map loads with all of my completed quests.  Just noticed that I can not check the quests manually, but I guess this is unrelated to this issue.

**Comment by reubengann** [comment]
Ok, thanks. I will make that change.

I have done some work on another branch to fix manual mode, but that branch
doesn't yet incorporate save file reading.

**Comment by reubengann** [comment]
Done. Sorry for the delay. Please test and let me know if there are any issues.

I am working on a major code overhaul, and kinda hoped to have it done before the next-gen release ... Life got in the way but the new version is getting there.

**Comment by muktesid** [comment]
I still have the issue after the hotfix

**Comment by reubengann** [comment]
Can you upload your save file?

**Comment by muktesid** [comment]
[ManualSave_fb036_7e70a400_4b91fc2.zip](https://github.com/reubengann/Witcher3MapViewer/files/10713692/ManualSave_fb036_7e70a400_4b91fc2.zip)

**Comment by reubengann** [comment]
Can you please try this release? https://github.com/reubengann/Witcher3MapViewer/releases/tag/0.5.1

**Comment by muktesid** [comment]
thank you very much
________________________________
Gönderen: reubengann ***@***.***>
Gönderildi: 11 Şubat 2023 Cumartesi 19:55
Kime: reubengann/Witcher3MapViewer ***@***.***>
Bilgi: muktesid ***@***.***>; Comment ***@***.***>
Konu: Re: [reubengann/Witcher3MapViewer] Fail to start on automatic mode (Issue #18)


Can you please try this release? https://github.com/reubengann/Witcher3MapViewer/releases/tag/0.5.1
