### ISSUE TITLE
Won't launch on automatic mode

### ISSUE THREAD

**Issue by DeathBoy54TR** [reubengann/Witcher3MapViewer#22]
Hi thanks for doing such a great program, I have a issue  can't use program in automatic mode it won't launch but in manual mode it works perfect how to fix it?

[ManualSave_55607_7e746800_10bd9aa.zip](https://github.com/reubengann/Witcher3MapViewer/files/12738066/ManualSave_55607_7e746800_10bd9aa.zip)

**Comment by reubengann** [comment]
Looks like they added something to the file format in a recent update. Fix incoming

**Comment by reubengann** [comment]
Please try the new release https://github.com/reubengann/Witcher3MapViewer/releases/tag/v0.62 and let me know if that helps

**Comment by DeathBoy54TR** [comment]
Thanks for still keeping up to support and for being fast, It works fine.

**Comment by DeathBoy54TR** [comment]
Thanks for still keeping up to support and for being fast, It works fine.
