### ISSUE TITLE
No X/Y coordinates?

### ISSUE THREAD

**Issue by MyNameIsAres** [reubengann/Witcher3MapViewer#24]
Just launched it and I've been playing around with it extensively. However, I cannot for the life of me get the X/Y coordinates to show up in the bottom right. 
![noxy](https://github.com/reubengann/Witcher3MapViewer/assets/32432637/047c26bd-11cb-4d39-8b07-04249141698d)

**Comment by reubengann** [comment]
Sorry, I deprecated that functionality as I assumed nobody used it. Is that
an important function for you?

**Comment by MyNameIsAres** [comment]
Thank you for your quick response! I just needed a tool to get the X/Y coordinates of certain places on the map. Is there an older release which still has this function?

**Comment by reubengann** [comment]
Unfortunately, not one that will still work on current saves. I can put the
function back in if it's being used. You also can look in the MapPins.xml
to see the coordinates of nearby points of interest to get an idea of where
you want to go.

**Comment by MyNameIsAres** [comment]
Forgot to close this - thank you! I'll have a look at that :)
