### ISSUE TITLE
App crashes when reading save files with typecode 19

### ISSUE THREAD

**Issue by RatQueen1** [reubengann/Witcher3MapViewer#5]
I double click the witcher3mapviewer app and the first time it worked immediately and i set it to automatic and it closed. After that i cannot open it.

**Comment by reubengann** [comment]
I have never seen this behavior. Can you please delete your settings and
retry? Did you receive an error?

**Comment by RatQueen1** [comment]
How do i delete the settings? I did not get an error at any point.

**Comment by reubengann** [comment]
Assuming you are on a modern version of Windows, it's
C:\Users\username\AppData\Local\Witcher3MapViewer

A number of pieces of information would help me in assessing why this is happening:
Which version of Windows are you on? Is it 64 or 32 bit?
Which version of .net do you have installed?
Which version of the game do you have installed? Through which service?

Also please attach your most recent save file to the post so I can do some forensics.

If the issue persists, it would be helpful for you to clone the repo and try launching it in VS so that you get debug messages.

**Comment by RatQueen1** [comment]
i am on windows 10 and am using 64 bit. I have the most recent witcher 3 update through steam. unsure about which .net i have, I also cannot attach the save file for some reason but if it helps i am about 2/3 of the way done through the game

**Comment by RatQueen1** [comment]
i now can open the map in manual mode but cannot actually check off the quests

**Comment by reubengann** [comment]
If the process is failing to parse your save file then I would actually need that file to troubleshoot.

**Comment by RatQueen1** [comment]
github is not letting me add the file

**Comment by reubengann** [comment]
Ok, please email the latest save and status.dat from your program folder to reubengann@gmail.com

**Comment by RatQueen1** [comment]
where is the status.dat?

**Comment by reubengann** [comment]
Yours is the first save file I have seen where the typecode can consist of 40 00 00 00 13 00 00 00 a3 00 00 00 instead of 40 00 00 00 12 00 00 00 a3 00 00 00. Can you provide any additional information why that might be? Are you in NewGame+? Is this a different region perhaps?

**Comment by RatQueen1** [comment]
i honestly have no idea, i am not in NG+ and i can only think of the fact that i have all the dlc as anything that might change it

**Comment by reubengann** [comment]
Can you compile the app with the new commit and see if that fixes your issue? It works on my system now.

**Comment by RatQueen1** [comment]
how would i do that?

**Comment by RatQueen1** [comment]
also sorry for being pretty tech illiterate with this stuff

**Comment by reubengann** [comment]
It's fine. I added a pre-release to the releases. Can you try it out?

**Comment by RatQueen1** [comment]
it worked! Thank you so much!

**Comment by reubengann** [comment]
Thanks for reporting. On next release (whenever that happens...) I'll add better notification when a file read fails.
