### ISSUE TITLE
File reader can't handle CSSPPL tag in Porp data type

### ISSUE THREAD

**Issue by TH3xL3G3NDx** [reubengann/Witcher3MapViewer#7]
Hello! 
I've been having issues in using this app. 
First, in manual mode I can't seem to select any of the boxes.
The second issue is automatic mode doesn't seem to work at all. If it is selected, the app closes and will not reopen unless I delete the config file in Local Data.
Any help would be appreciated!

**Comment by reubengann** [comment]
Hi. Which build are you using? If you're using the stable build, please try the latest unstable one. It fixes a file opening problem. If you're already using the most recent one, please send me your save file so I can troubleshoot.

**Comment by TH3xL3G3NDx** [comment]
I was using the stable one. I switched to the latest unstable and it seems to be working! The only thing not working is that I can't manually check things off when in automatic mode, which already seems to be a bug issue. Thank you for the quick response and help, I love the app, great work!

**Comment by TH3xL3G3NDx** [comment]
Update. So the app was working perfectly until I leveled up to level 2. As soon as I leveled (the main quest updated as well) the application crashed and reverts back to the original issue of not being able to reopen it until the config file is deleted. 

[ManualSave_53db9_7e343000_2d112f6.zip](https://github.com/reubengann/Witcher3MapViewer/files/3610876/ManualSave_53db9_7e343000_2d112f6.zip)

**Comment by reubengann** [comment]
Do you have any mods or anything else nonstandard about your install? You have a data type CSSPPL that I've never seen before.

**Comment by TH3xL3G3NDx** [comment]
Yes, I am using a decent amount of mods however I've had the mods installed since level 1 and the app worked with them.  I appreciate the help!

**Comment by reubengann** [comment]
Please test the newest unstable build and let me know if it helps.

**Comment by TH3xL3G3NDx** [comment]
It read my save file and seems to be working so far! I'll be sure to update you if the issue seems to occur again. I greatly appreciate the quick response and help and the amazing tool, props to you!

**Comment by reubengann** [comment]
Glad to hear. I hope you can appreciate that I can't support every mod out there, so if you run into further problems you may need to go back to a vanilla install.
