### ISSUE TITLE
Crash on loading in automatic mode.

### ISSUE THREAD

**Issue by tab8081** [reubengann/Witcher3MapViewer#8]
I'm getting an immediate crash when I hit "Save & Close" after setting the program to Automatic mode. My game's got quite a few mods on it, but I don't believe any of them affect quests.

I've attached the save file that it's theoretically trying to load when it crashes.

[ManualSave_5258a_7e402c00_42f4834.zip](https://github.com/reubengann/Witcher3MapViewer/files/4051601/ManualSave_5258a_7e402c00_42f4834.zip)

**Comment by reubengann** [comment]
Thanks for reporting. Are you using the latest build?

**Comment by tab8081** [comment]
That was on the stable release. Seems to be fixed on the unstable build.

**Comment by reubengann** [comment]
Ok. I will bump the latest release since it's been in the wild for awhile and seems fine.
